# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hyuhng Joon Kim
title: Master's student, Seoul National University
email: heyjoonkim@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: heyjoonkim1
github_username:  heyjoonkim
instagram_username: jour_vert_
linkedin_username: hyuhng-joon-kim-802624168
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Hyuhng Joon Kim. I'm a Master's student in [Graduate School of AI](https://gsai.snu.ac.kr/), [Seoul National University](https://www.snu.ac.kr/). 
  
  I'm interested in <mark>Natural Language Processing</mark>.

content:
  - title: Educations / Careers
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Seoul National University
        caption: 2020 - Present
        #sub_title: MSc Graduate School of AI
        description: | # this will include new lines to allow paragraphs
          MSc in Graduate School of AI
          
          [Intelligent Data System Laboratory](http://ids.snu.ac.kr/site/), Advisor [Sang-goo Lee](http://ids.snu.ac.kr/site/members/M_Sang-goo_Lee.html)
          
      - layout: left
        title: T.A. Experience
        caption: 2020 - Present
        #sub_title: BSc Computer Science and Engineering
        description: | # this will include new lines to allow paragraphs
          SNU Samsung DS^2 (2021.01)
          
      - layout: left
        title: Bigdata Cloud Lab.
        caption: 2018 - 2020
        #sub_title: BSc Computer Science and Engineering
        description: | # this will include new lines to allow paragraphs
          Undergraduate research student
          
      - layout: left
        title: Military Service
        caption: 2015 - 2017
        #sub_title: BSc Computer Science and Engineering
        description: | # this will include new lines to allow paragraphs
          Served and discharged from The 7th Infantry Division, ROK Army.
          
      - layout: left
        title: Soongsil University
        caption: 2014 - 2020
        #sub_title: BSc Computer Science and Engineering
        description: | # this will include new lines to allow paragraphs
          BSc in Computer Science and Engineering
          
      - layout: left
        title: Shinil High School
        caption: 2011 - 2014
        
      - layout: left
        title: Radnor High School
        caption: 2010 - 2011

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
